name: Daily GitHub Trending to Feishu

on:
  schedule:
    # 每天早上 8:00 触发 (UTC 时间 0:00)
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动点击运行测试

jobs:
  push_trending:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        # 修复此处的参数名，从 python-state 改为 python-version
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run Python Script
      env:
        FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
        FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
        FEISHU_RECEIVER_MOBILE: ${{ secrets.FEISHU_RECEIVER_MOBILE }}
      run: python trending.py
